---
action: 
indicator: submit
auto_fieldset: 1
localize_class: MojoMojo::I18N

elements:
  - type: Text
    name: name
    label_loc: Site name
    filters:
       - HTMLEscape
    constraints:
      - Required
  - type: Text
    name: admins
    label_loc: Site Admins (In addition to you)
  - type: Text
    name: anonymous_user
    label_loc: Anonymous User (blank to disable)
  - type: Checkbox
    name: open_registration
    label_loc: New User Registration open
    value: 1
    default_empty_value: 0
  - type: Checkbox
    name: restricted_user
    value: 1
    default_empty_value: 0
    label_loc: Restrict user editing to home directory
  - type: Checkbox
    name: use_captcha
    label_loc: Use captcha
    value: 1
    default_empty_value: 0
  - type: Submit
    name: submit
    value_loc: Save
