---
action: 
indicator: submit
auto_fieldset: 1

elements:
  - type: Text
    name: name
    label: Site name
    filters:
       - HTMLEscape
    constraints:
      - Required
  - type: Text
    name: admins
    label: Site Admins (In addition to you)
  - type: Text
    name: anonymous_user
    label: Anonymous User (blank to disable)
  - type: Checkbox
    name:
